version: "3.7"

networks:
        web:
                external: true
        internal:
                external: false
                driver: bridge

services:
        caddy:
                image: caddy:2-alpine
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./Caddyfile:/etc/caddy/Caddyfile
                        - ./data:/data # Optional
                        - ./config:/config # Optional
                networks:
                        - web
                        - internal
        ghost:
                image: ghost:4-alpine
                restart: unless-stopped
                environment:
                        - url=https://ghost.furyhawk.lol # Change to your domain
                volumes:
                        - ./ghostapp:/var/lib/ghost/content
                networks:
                        - internal